"""Permutation test for significance of the empirical eigenvalue spectrum.

Tests H0: genes are mutually independent (no gene-gene correlation structure),
against the alternative that the top of the correlation spectrum carries signal.

The null is generated by the same column-wise scramble used to build ev_data/
(src/analysis_functions.scramble): each gene's values are independently permuted
across cells, which preserves every gene's marginal exactly and destroys only
cross-gene dependence. Unlike a bulk test (KS), the statistics here target the
top of the spectrum, where the entire signal lives.

Preprocessing is validated to reproduce ev_data/*.npy; see the per-sample
"validation" block in results/permutation_test/logs/*.json.

Statistics (all p-values from the same permutation null):
  lambda_1     largest eigenvalue (Roy's largest root)
  z_k          (lambda_obs[k] - mean_null[k]) / sd_null[k]
  topK_mass    sum of the top K eigenvalues
  maxT         max over ranks k<=K of z_k, with the max taken inside every
               replicate -> FWER control across the K ranks
  k_hat        parallel analysis: number of leading eigenvalues that exceed the
               95th percentile of the null at their own rank

Outputs -> results/permutation_test/{raw,logs,figures}/
"""
import os
import sys
import json
import time
import platform
from datetime import datetime

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.stats import mannwhitneyu

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import null_distribution_fit as ndf

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _REPO)
import src.data_functions as data_func
import src.analysis_functions as af

# ---------------------------------------------------------------- parameters
B = 100                 # permutation replicates
K = 20                  # ranks used for topK_mass and maxT (~1% of p)
K_SCAN = None           # ranks retained per replicate for the k_hat scan;
                        # None = the full spectrum (all n nonzero eigenvalues)
SEED = 20260823
ALPHA = 0.05
TRACKER_GENES = ['16s_mature', '16s_unprocessed', 'LELOBEKK']   # as in test.ipynb
NORM_METHOD, NORM_SUM, LOG = 'sum', 1, False                    # get_eig_dist defaults
MIN_CELLS, MIN_GENES = 1, 1

DATA_DIR = os.path.join(_REPO, 'data_for_paper')
EV_DIR = os.path.join(_REPO, 'ev_data')
OUT = os.path.join(_REPO, 'results', 'permutation_test')
STAMP = datetime.now().strftime('%Y%m%d_%H%M%S')
TAG = 'eigenvalue_permutation_test_' + STAMP


# ---------------------------------------------------------------- pipeline
def load_matrix(path):
    """Reproduce get_data_for_plot() from scripts/test.ipynb exactly."""
    amat = data_func.read_from_csv(path)
    idx = [np.where(amat.var_names == v)[0][0] for v in TRACKER_GENES if v in amat.var_names]
    amat.filtered_var[np.array(idx).astype(int)] = False
    dropped = [v for v in TRACKER_GENES if v in amat.var_names]
    return amat.get_filtered_matrix().m.astype(float), dropped


def prep(m):
    """Preprocessing of af.get_eig_dist: filter -> row-sum normalize -> column z-score."""
    m = m[:, (m > 0).sum(0) >= MIN_CELLS]
    m = m[(m > 0).sum(1) >= MIN_GENES, :]
    m = m / m.sum(1)[:, None]
    m[np.isnan(m)] = 0
    m = (m - m.mean(0)) / m.std(0)
    m[np.isnan(m)] = 0
    return m


def spec(m):
    """Nonzero eigenvalues of the gene-gene correlation matrix (1/n)M'M, descending.

    Computed from the n x n Gram matrix, which shares all nonzero eigenvalues with
    the p x p correlation matrix but is much smaller since n < p. Equivalent to
    af.get_pcs()'s svd(m)[1]**2/n, minus the p-n structural zeros.
    """
    n = m.shape[0]
    return np.sort(np.linalg.eigvalsh(m @ m.T / n))[::-1]


def scramble(m, rng):
    """Column-wise permutation: src/analysis_functions.scramble with an explicit RNG."""
    return np.column_stack([rng.permutation(c) for c in m.T])


def perm_pvalue(null_vals, obs):
    """(1 + #{null >= obs}) / (B + 1): the observed data counts as its own permutation."""
    return float((1 + np.sum(null_vals >= obs)) / (len(null_vals) + 1))


# ---------------------------------------------------------------- validation
def validate(m_raw, M, stored_pcs):
    """Confirm this preprocessing reproduces the stored ev_data spectrum."""
    pcs_repo, _, _ = af.get_eig_dist(m_raw, norm=True, log=LOG,
                                     norm_method=NORM_METHOD, norm_sum=NORM_SUM)
    padded = np.zeros(M.shape[1])
    s = spec(M)
    padded[:len(s)] = s
    return dict(
        len_match=bool(len(pcs_repo) == len(stored_pcs) == len(padded)),
        max_abs_diff_repo_vs_stored=float(np.abs(pcs_repo - stored_pcs).max()),
        max_abs_diff_this_vs_stored=float(np.abs(padded - stored_pcs).max()),
        trace_this=float(padded.sum()),
        trace_stored=float(stored_pcs.sum()),
    )


# ---------------------------------------------------------------- main
def run():
    titles = pd.read_excel(os.path.join(EV_DIR, 'titles.xlsx')).set_index('file_name')
    rng = np.random.default_rng(SEED)

    samples = sorted(f[:-4] for f in os.listdir(DATA_DIR) if f.endswith('.csv'))
    ev_only = sorted(f[:-4] for f in os.listdir(EV_DIR)
                     if f.endswith('.npy') and not f.startswith('simulated')
                     and not os.path.exists(os.path.join(DATA_DIR, f[:-4] + '.csv')))

    per_sample, table = {}, []
    null_draws_store = {}
    t_start = time.time()

    for name in samples:
        t0 = time.time()
        stored = np.load(os.path.join(EV_DIR, name + '.npy'))[0]
        m_raw, dropped = load_matrix(os.path.join(DATA_DIR, name + '.csv'))
        M = prep(m_raw)
        n, p = M.shape
        obs = spec(M)

        val = validate(m_raw, M, stored)
        assert val['max_abs_diff_repo_vs_stored'] == 0.0, name + ': repo pipeline mismatch'
        assert val['max_abs_diff_this_vs_stored'] < 1e-10, name + ': preprocessing mismatch'

        k_scan = len(obs) if K_SCAN is None else min(K_SCAN, len(obs))
        null = np.empty((B, k_scan))
        for b in range(B):
            null[b] = spec(scramble(M, rng))[:k_scan]

        mu_all, sd_all = null.mean(0), null.std(0)
        z_all = (obs[:k_scan] - mu_all) / sd_all
        mu, sd, z_obs = mu_all[:K], sd_all[:K], z_all[:K]
        p_k = np.array([perm_pvalue(null[:, k], obs[k]) for k in range(K)])

        T_obs, T_null = obs[:K].sum(), null[:, :K].sum(1)
        p_topK = perm_pvalue(T_null, T_obs)

        maxT_obs = z_obs.max()
        maxT_null = ((null[:, :K] - mu) / sd).max(1)
        p_maxT = perm_pvalue(maxT_null, maxT_obs)

        # parametric tail probability: fit a law to the B scrambled lambda_k and
        # read off SF(lambda_obs_k), instead of counting exceedances (censored at 1/(B+1))
        fit_k = [ndf.parametric_pvalue(null[:, k], obs[k], B=B) for k in range(K)]
        calib = ndf.calibration_check(null[:, 0], seed=SEED)
        null_draws_store[name] = null[:, :K].copy()

        # parallel analysis over the wider scan; censored if it reaches k_scan
        q95 = np.quantile(null, 1 - ALPHA, axis=0)
        above = obs[:k_scan] > q95
        k_hat = k_scan if above.all() else int(np.argmin(above))
        k_hat_censored = bool(above.all())

        title = titles.title.get(name + '.npy', name)
        cat = titles.category.get(name + '.npy', '?')
        el = time.time() - t0
        per_sample[name] = dict(
            title=title, category=cat, n_cells=int(n), n_genes=int(p),
            dropped_tracker_genes=dropped, validation=val,
            lambda_obs_topK=obs[:K].tolist(),
            null_mean_topK=mu.tolist(), null_sd_topK=sd.tolist(),
            null_q95_topK=q95[:K].tolist(), z_topK=z_obs.tolist(),
            p_per_rank_topK=p_k.tolist(),
            parametric_fit_topK=fit_k,
            null_fit_calibration_rank1=calib,
            lambda_1=float(obs[0]), z_1=float(z_obs[0]),
            p_lambda_1_empirical=float(p_k[0]),
            p_lambda_1=float(fit_k[0]['p_parametric']),
            log10_p_lambda_1=float(fit_k[0]['log10_p_parametric']),
            best_family_rank1=fit_k[0]['best_family'],
            topK_mass_obs=float(T_obs), topK_mass_null_mean=float(T_null.mean()),
            topK_mass_null_sd=float(T_null.std()), p_topK_mass=p_topK,
            maxT_obs=float(maxT_obs), maxT_rank=int(np.argmax(z_obs) + 1), p_maxT=p_maxT,
            k_hat_parallel_analysis=k_hat, k_hat_censored_at_k_scan=k_hat_censored,
            k_scan=int(k_scan), runtime_sec=round(el, 1),
        )
        f1 = fit_k[0]
        table.append(dict(sample=name, title=title, cat=cat, n=n, p=p,
                          lambda_1=obs[0], null_mean=mu[0], null_sd=sd[0], z_1=z_obs[0],
                          best_family=f1['best_family'], fit_ks_p=f1['best_ks_p'],
                          p_lambda_1=f1['p_parametric'],
                          log10_p_lambda_1=f1['log10_p_parametric'],
                          log10_p_lo=f1['log10_p_min'], log10_p_hi=f1['log10_p_max'],
                          family_spread_orders=f1['family_spread_orders'],
                          extrapolated=f1['extrapolated'],
                          p_lambda_1_empirical=p_k[0],
                          topK_mass=T_obs, p_topK_mass=p_topK,
                          maxT=maxT_obs, p_maxT=p_maxT, k_hat=k_hat,
                          k_hat_censored=k_hat_censored,
                          pit_ks_p=calib.get('pit_ks_p')))
        print('{:30s} n={:5d}  lam1={:7.3f}  z1={:8.2f}  fit={:10s} '
              'log10(p)={:9.2f} [{:.1f},{:.1f}]  p_emp={:.4f}  k_hat={:3d} ({:.0f}s)'
              .format(name, n, obs[0], z_obs[0], f1['best_family'],
                      f1['log10_p_parametric'], f1['log10_p_min'], f1['log10_p_max'],
                      p_k[0], k_hat, el), flush=True)

    df = pd.DataFrame(table)

    # group-level test: is the correlation signal weaker in dysregulated samples?
    gr = df[df.cat == 'r'].z_1.values
    gd = df[df.cat == 'd'].z_1.values
    u, p_mw = mannwhitneyu(gd, gr, alternative='less')
    group = dict(statistic='z_1', n_regulated=len(gr), n_dysregulated=len(gd),
                 median_z1_regulated=float(np.median(gr)),
                 median_z1_dysregulated=float(np.median(gd)),
                 mannwhitney_U=float(u), p_value=float(p_mw),
                 alternative='dysregulated < regulated (one-sided)')

    # ------------------------------------------------------------ outputs
    df.to_csv(os.path.join(OUT, 'raw', TAG + '.csv'), index=False)
    np.savez_compressed(os.path.join(OUT, 'raw', TAG + '_null_draws.npz'), **null_draws_store)

    with open(os.path.join(OUT, 'raw', TAG + '.txt'), 'w') as f:
        f.write('Eigenvalue spectrum permutation test\n' + '=' * 78 + '\n')
        f.write('run: {}   B={}   K={}   seed={}   alpha={}\n'.format(STAMP, B, K, SEED, ALPHA))
        f.write(
            'p_lambda_1 is PARAMETRIC: a distribution family is fitted by MLE to the B\n'
            'scrambled values of lambda_1 and p = SF_fitted(lambda_obs_1). Family chosen\n'
            'by AIC. log10_p_lo/hi bracket the answer across every fitted family: the\n'
            'lightest tail (normal) gives the smallest p, the heaviest (Gumbel/lognormal)\n'
            'the largest. Tracy-Widom, the theoretical law for the largest eigenvalue of\n'
            'a Wishart-type null, has right tail exp(-(2/3)s^1.5) and so lies BETWEEN the\n'
            'normal exp(-s^2/2) and the Gumbel exp(-s): the band contains the truth.\n'
            'extrapolated=True marks p < 1/B, where the value follows from the assumed\n'
            'tail shape rather than from the null sample -- read those as "below what\n'
            'B={} draws can resolve", not as the numeral.\n'
            'p_lambda_1_empirical is the exceedance count, censored at 1/(B+1) = {:.4f}.\n'
            'pit_ks_p is a held-out calibration check of the fit over its OBSERVABLE\n'
            'range (fit on half the draws, PIT the other half); large = no misfit\n'
            'detected where data exist. It cannot validate the far tail.\n\n'
            .format(B, 1 / (B + 1)))
        f.write("Preprocessing validated against ev_data/*.npy: exact (max abs diff 0.0 vs.\n"
                "the repo's own af.get_eig_dist; <1e-13 for the Gram-matrix route).\n\n")
        f.write(df.to_string(index=False, float_format=lambda x: '{:.4f}'.format(x)))
        f.write('\n\nlog10(p) for lambda_1 under every fitted family '
                '(lightest tail first -> smallest p):\n')
        f.write('  {:28s} '.format('sample') +
                '  '.join('{:>10s}'.format(fam) for fam in ndf.TAIL_ORDER) + '\n')
        for nm, v in per_sample.items():
            pf = v['parametric_fit_topK'][0]['per_family']
            f.write('  {:28s} '.format(v['title'][:28]) + '  '.join(
                ('{:10.1f}'.format(pf[fam]['log10_p']) if fam in pf else '{:>10s}'.format('-'))
                for fam in ndf.TAIL_ORDER) + '\n')
        f.write('\n\nGroup comparison (Mann-Whitney U on z_1, dysregulated < regulated):\n')
        for k, v in group.items():
            f.write('  {}: {}\n'.format(k, v))
        if ev_only:
            f.write('\nDatasets in ev_data/ with no source matrix in data_for_paper/ '
                    '(not testable):\n')
            for e in ev_only:
                f.write('  {}\n'.format(e))

    log = dict(
        experiment=TAG, timestamp=STAMP,
        description='Permutation test that the empirical eigenvalue spectrum differs '
                    'from the column-scrambled null, targeting the top of the spectrum.',
        null_hypothesis='genes are mutually independent (no gene-gene correlation)',
        null_construction='independent permutation of each gene (column) across cells; '
                          'reproduces src/analysis_functions.scramble',
        parameters=dict(
            B=B, K=K, K_SCAN=K_SCAN, seed=SEED, alpha=ALPHA, rng='numpy default_rng (PCG64)',
            tracker_genes_removed=TRACKER_GENES,
            normalization=dict(method=NORM_METHOD, target_sum=NORM_SUM, log=LOG),
            filtering=dict(min_cells_per_gene=MIN_CELLS, min_genes_per_cell=MIN_GENES),
            z_transform="column-wise, ddof=0 -> (1/n)M'M is the Pearson correlation "
                        "matrix with trace exactly p",
            eigen_solver="numpy.linalg.eigvalsh on the n x n Gram matrix (1/n)MM'",
            min_attainable_empirical_p=1 / (B + 1)),
        pvalue_method=dict(
            primary='parametric: MLE fit of a distribution family to the B scrambled '
                    'lambda_k, then p = SF_fitted(lambda_obs_k)',
            family_selection='AIC over ' + ', '.join(ndf.TAIL_ORDER),
            reported_band='log10_p_min (lightest tail) to log10_p_max (heaviest tail) '
                          'across all converged families',
            theory='for the largest eigenvalue of a Wishart-type null the limiting law is '
                   'Tracy-Widom (beta=1), right tail exp(-(2/3)s^{3/2}); heavier than the '
                   'normal tail exp(-s^2/2) and lighter than the Gumbel tail exp(-s), so '
                   'the normal and Gumbel fits bracket the Tracy-Widom answer',
            gamma_note='the 3-parameter gamma is included because the Chiani (2014) '
                       'approximation to Tracy-Widom is a shifted, scaled gamma, so a free '
                       'gamma fit can reach a Tracy-Widom-shaped solution',
            secondary='empirical permutation p = (1 + #{null >= obs}) / (B + 1), '
                      'censored at 1/(B+1)',
            calibration='held-out PIT check: fit on half the null draws, map the other '
                        'half through the fitted CDF, KS against Uniform(0,1); validates '
                        'the fit over its observable range only',
            caveat='p below 1/B extrapolates beyond the support of the null sample; its '
                   'value is determined by the assumed tail shape, so report the band'),
        statistics=dict(
            lambda_1='largest eigenvalue (Roy\'s largest root)',
            z_k='(lambda_obs[k] - null_mean[k]) / null_sd[k], null moments from the B replicates',
            topK_mass='sum of the top {} eigenvalues'.format(K),
            maxT='max over k<={} of z_k, maximized within each replicate '
                 '(FWER control across ranks)'.format(K),
            k_hat='parallel analysis: number of leading eigenvalues above the null '
                  '95th percentile at their own rank, scanned over the first '
                  '{} ranks (k_hat_censored flags samples that reach the scan '
                  'limit)'.format(K_SCAN or 'all')),
        environment=dict(python=platform.python_version(), numpy=np.__version__,
                         pandas=pd.__version__, platform=platform.platform()),
        datasets_tested=samples,
        datasets_in_ev_data_without_source_matrix=ev_only,
        group_comparison=group,
        total_runtime_sec=round(time.time() - t_start, 1),
        results=per_sample,
    )
    with open(os.path.join(OUT, 'logs', TAG + '.json'), 'w') as f:
        json.dump(log, f, indent=2)

    make_figure(df, per_sample, group, null_draws=null_draws_store)
    print('\nwrote results/permutation_test/{{raw,logs,figures}}/{}.*'.format(TAG))
    return df, group


def make_figure(df, per_sample, group, tag=None, null_draws=None):
    tag = tag or TAG
    colors = {'r': '#2c6fbb', 'd': '#c8412f'}
    d = df.sort_values(['cat', 'z_1'], ascending=[True, False]).reset_index(drop=True)

    fig = plt.figure(figsize=(16, 10.5))
    gs = fig.add_gridspec(2, 3, width_ratios=[1.5, 1, 1.2], height_ratios=[1.15, 1],
                          hspace=0.32, wspace=0.26)
    axes = [fig.add_subplot(gs[0, i]) for i in range(3)]
    axes_b = [fig.add_subplot(gs[1, i]) for i in range(3)]

    ax = axes[0]
    ax.barh(range(len(d)), d.z_1, color=[colors.get(c, 'grey') for c in d.cat])
    ax.axvline(0, color='k', lw=0.8)
    ax.set_yticks(range(len(d)))
    ax.set_yticklabels(d.title, fontsize=8)
    ax.invert_yaxis()
    ax.set_xscale('symlog', linthresh=1)
    ax.set_xlabel(r'$z_1 = (\lambda_1 - \mu_{null}) / \sigma_{null}$   (symlog)')
    ax.set_title('Largest eigenvalue vs. permutation null (B={})'.format(B), fontsize=10)
    for i, (z, l10) in enumerate(zip(d.z_1, d.log10_p_lambda_1)):
        # negative bars extend left of zero, so label them in the empty right half
        lab = ('p={:.2f}'.format(10 ** l10) if l10 > -3
               else r'$p{\sim}10^{%.0f}$' % l10)
        ax.text(z * 1.25 if z > 0 else 1.2, i, lab, va='center', ha='left', fontsize=6.5)
    ax.set_xlim(-3, 30000)

    ax = axes[1]
    for cat, lbl, xpos in [('r', 'regulated', 0), ('d', 'dysregulated', 1)]:
        v = df[df.cat == cat].z_1.values
        x = np.random.default_rng(0).normal(xpos, 0.06, len(v))
        ax.scatter(x, v, color=colors[cat], s=45, alpha=0.85, label=lbl, zorder=3)
        ax.hlines(np.median(v), xpos - 0.22, xpos + 0.22, color=colors[cat], lw=2.5, zorder=4)
    ax.axhline(0, color='k', lw=0.8, ls=':')
    ax.set_yscale('symlog', linthresh=1)
    ax.set_ylim(-3, 3000)
    ax.set_xlim(-0.6, 1.6)
    ax.set_xticks([0, 1])
    ax.set_xticklabels(['regulated', 'dysregulated'], fontsize=9)
    ax.set_ylabel('$z_1$  (symlog)')
    ax.set_title('Mann-Whitney one-sided p = {:.4f}'.format(group['p_value']), fontsize=10)

    ax = axes[2]
    for name in d['sample']:
        r = per_sample[name]
        ax.plot(range(1, K + 1), r['z_topK'], marker='o', ms=2.5, lw=1,
                color=colors.get(r['category'], 'grey'), alpha=0.8)
    ax.axhline(0, color='k', lw=0.8, ls=':')
    ax.set_yscale('symlog', linthresh=1)
    ax.set_ylim(-3, 3000)
    ax.set_xlabel('eigenvalue rank $k$')
    ax.set_ylabel('$z_k$  (symlog)')
    ax.set_xticks([1, 5, 10, 15, 20])
    ax.set_title('Rank profile of the deviation from null', fontsize=10)

    # ---- bottom row: the fitted null law and where the observation falls
    demo = [('Expira_biorep_t0A_filtered', 'strong signal'),
            ('SHX_biorep2B', 'weak signal'),
            ('sample_15a_filtered', 'no signal')]
    for ax_b, (nm, lbl) in zip(axes_b, demo):
        if nm not in per_sample or null_draws is None or nm not in null_draws:
            ax_b.axis('off')
            continue
        r = per_sample[nm]
        f1 = r['parametric_fit_topK'][0]
        draws = np.asarray(null_draws[nm])[:, 0]
        ax_b.hist(draws, bins=22, density=True, color='0.82', edgecolor='0.45', lw=0.4,
                  label='scrambled $\\lambda_1$ (B={})'.format(len(draws)))
        pad = 4 * draws.std()
        xs = np.linspace(draws.min() - pad, draws.max() + pad, 500)
        for fam, style in [(f1['best_family'], '-'), ('norm', '--'), ('gumbel_r', ':')]:
            pars = (f1['best_params'] if fam == f1['best_family']
                    else ndf.fit_null(draws, [fam]).get(fam, {}).get('params'))
            if pars is None:
                continue
            ax_b.plot(xs, ndf.CANDIDATES[fam].pdf(xs, *pars), style, lw=1.6,
                      label=fam + (' (AIC best)' if fam == f1['best_family'] else ''))
        obs1 = r['lambda_1']
        ax_b.axvline(obs1, color='#c8412f', lw=2,
                     label='observed $\\lambda_1$ = {:.2f}'.format(obs1))
        lo, hi = min(xs.min(), obs1), max(xs.max(), obs1)
        ax_b.set_xlim(lo - 0.05 * (hi - lo), hi + 0.05 * (hi - lo))
        ax_b.set_title('{} — {}\n$z_1$={:.1f},  $\\log_{{10}}p$={:.1f}  '
                       '(band {:.0f} to {:.0f})'.format(
                           r['title'], lbl, r['z_1'], f1['log10_p_parametric'],
                           f1['log10_p_min'], f1['log10_p_max']), fontsize=9)
        ax_b.set_xlabel('$\\lambda_1$')
        ax_b.set_ylabel('density')
        ax_b.legend(fontsize=6.5, loc='upper right')

    for ext in ('svg', 'png'):
        fig.savefig(os.path.join(OUT, 'figures', tag + '.' + ext), dpi=200, bbox_inches='tight')
    plt.close(fig)


def replot(json_path):
    """Regenerate the figure from a saved log, without recomputing the permutations."""
    with open(json_path) as f:
        log = json.load(f)
    per_sample = log['results']
    df = pd.DataFrame([
        dict(sample=k, title=v['title'], cat=v['category'], n=v['n_cells'], p=v['n_genes'],
             lambda_1=v['lambda_1'], null_mean=v['null_mean_topK'][0],
             null_sd=v['null_sd_topK'][0], z_1=v['z_1'], p_lambda_1=v['p_lambda_1'],
             topK_mass=v['topK_mass_obs'], p_topK_mass=v['p_topK_mass'],
             maxT=v['maxT_obs'], p_maxT=v['p_maxT'], k_hat=v['k_hat_parallel_analysis'],
             log10_p_lambda_1=v['log10_p_lambda_1'])
        for k, v in per_sample.items()])
    npz = json_path.replace('logs', 'raw').replace('.json', '_null_draws.npz')
    draws = dict(np.load(npz)) if os.path.exists(npz) else None
    make_figure(df, per_sample, log['group_comparison'], tag=log['experiment'],
                null_draws=draws)
    print('replotted', log['experiment'])


if __name__ == '__main__':
    if len(sys.argv) > 2 and sys.argv[1] == '--replot':
        replot(sys.argv[2])
    else:
        run()
